version: '3'
name: traefik

services:
  reverse-proxy:
    image: traefik:v3.1
    container_name: traefik

    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker

    ports:
      - "80:80" # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      # - /opt/traefik/traefik.yml:/traefik.yml:ro
      # - /opt/traefik/config.yml:/config.yml:ro
    networks:
      - traefik

networks:
  traefik:
   external: true
